const tape = require('tape')
const { PassThrough } = require('stream')
const hashtagStreamSet = require('./index.js')

tape('add', t => {
  const set = hashtagStreamSet()
  set.add('#fraud', new PassThrough())
  set.add('#fraud', new PassThrough())
  set.add('#money', new PassThrough())
  t.equal(set.size, 3, 'size 3')
  set.forEach((stream, i) => {
    t.ok(stream._hashtag, 'set a _hashtag prop')
    if (i === set.size - 1) t.end()
  })
})

tape('delete', t => {
  const set = hashtagStreamSet()
  const a = new PassThrough()
  const b = new PassThrough()
  const c = new PassThrough()
  set.add('#fraud', a, b)
  set.add('#money', c)
  t.equal(set.size, 3, 'size 3')
  set.delete('#fraud')
  t.equal(set.size, 1, 'size 1')
  set.delete('#money')
  t.equal(set.size, 0, 'size 0')
  ;[ a, b, c ].forEach((stream, i, arr) => {
    t.notOk(stream._hashtag, '_hashtag prop undefined')
    if (i === arr.length - 1) t.end()
  })
})

tape('willDelete', t => {
  const set = hashtagStreamSet()
  const a = new PassThrough()
  const b = new PassThrough()
  const c = new PassThrough()
  set.add('#fraud', a, b)
  set.add('#money', c)
  set.delete('#money', (tag, del_streams, doDelete) => {
    t.equal(del_streams.length, 1, 'del_streams.length 1')
    t.equal(set.size, 3, 'set size still 3')
    del_streams.forEach(stream => stream.destroy())
    doDelete()
    t.equal(set.size, 2, 'set size down to 2')
    t.end()
  })
})
